# 端口
server:
  port: 8201
spring:
  # json转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#阿里云oss配置，自定义
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tRxUsKyCCf8psYZ7AC1
    secret: hoGgTYs5cGgoU8EsMs2B4BaJNG0n4T
    bucket: bylw-wjq
