# 服务端口
server:
  port: 91

spring:
  application:
    name: service-gateway

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes[0]:
        id: service-hosp
        uri: lb://service-hosp
        predicates: Path=/*/hosp/**